# 配置文件

DAILY_TIME: "14:00" # 每日定时发送时间。该时间为系统时间，如果当前系统时间不为北京时间需要自行进行换算

START_DATE: "2019-11-30" # 纪念日
CITY: "青岛"

BIRTHDAY:
  - "12-26"

APP_ID: "wx6092d04aad8accf9"
APP_SECRET: "6d911eabd8c97f5e9bfff5b6599168e0"

USER_ID: 
  - ohP-76QhsmC-kXgpj0W7Wssx2gIc"
  - "USER ID 2" # 你可以通过配置多个USER_ID来设置多个接受者，如果接受者只有一人删除本行即可
TEMPLATE_ID: "XOCX95Pg1PSmplrg_cUUIKhOrjCKQhqcIOHA8SDtDWE"
